# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588408d61bdbfff36e41ce590312758092af53fc723a3e60f17862be2a99c0d660f15fb71e282b5a0ab261804135c19d29713c355822e021183e3b44da8de413

test:
  secret_key_base: 57dc8ff0328ca278f3f65beced45f8b30dbadc2936bf19dbe51358c6ddd4fbd59f15bb6acaa0b3a0b328429c8ba973dd071817d3953e04c50de4645207884644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
